name: CD Pipeline

on:
  workflow_run:
    workflows: "Docker Image CI"
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Pull Docker Image
        run: sudo docker pull ashwanthsai/sydneyflixtest:latest

      - name: Delete Old Docker Container
        run: sudo docker rm -f production || true

      - name: Run Docker Container
        run: sudo docker run -d -p 80:80 --name production ashwanthsai/sydneyflixtest