name: CD Pipeline
on:
  workflow_run:
    workflows: ["Unit + Integration Tests via RTL", "E2E Via Cypress", "Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Pull Docker Image
        run: sudo docker pull ashwanthsai/sydneyflix:latest || exit 1

      - name: Delete Old Docker Container
        run: sudo docker rm -f production || true

      - name: Run Docker Container
        run: |
          sudo docker run -d \
            -p 80:80 \
            --name production \
            --restart unless-stopped \
            -e REACT_APP_TMDBKEY=${{ secrets.REACT_APP_TMDBKEY }} \
            -e REACT_APP_ALAN_KEY=${{ secrets.REACT_APP_ALAN_KEY }} \
            -e TMDB_TEST_EMAIL=${{ secrets.TMDB_TEST_EMAIL }} \
            -e TMDB_TEST_PASSWORD=${{ secrets.TMDB_TEST_PASSWORD }} \
            -e PROJECT_ID=${{ secrets.PROJECT_ID }} \
            ashwanthsai/sydneyflix:latest
