name: CD Pipeline
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Pull Docker Image
        run: sudo docker pull ashwanthsai/sydneyflix:latest || exit 1

      - name: Delete Old Docker Container
        run: sudo docker rm -f production || true

      - name: Run Docker Container
        run: |
          sudo docker run -d \
          -p 3000:3000 \
          --name production \
          --restart unless-stopped \
          -e REACT_APP_TMDBKEY=${{ secrets.REACT_APP_TMDBKEY }} \
          -e REACT_APP_ALAN_KEY=${{ secrets.REACT_APP_ALAN_KEY }} \
          -e TMDB_TEST_EMAIL=${{ secrets.TMDB_TEST_EMAIL }} \
          -e TMDB_TEST_PASSWORD=${{ secrets.TMDB_TEST_PASSWORD }} \
          -e PROJECT_ID=${{ secrets.PROJECT_ID }} \
          ashwanthsai/sydneyflix:latest
# Prevents mege without dockerization and deployment
      - name: Report Deployment Status
        uses: actions/github-script@v7
        with:
          script: |
            const result = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Deployment Status',
              head_sha: context.sha,
              status: 'completed',
              conclusion: 'success'
            });
