name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]  # Add brackets for array
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Pull Docker Image
        run: sudo docker pull ashwanthsai/sydneyflixtest:latest

      - name: Delete Old Docker Container
        run: sudo docker rm -f production || true

      - name: Run Docker Container
        run: |
          sudo docker run -d \
            -p 80:80 \
            --name production \
            --restart unless-stopped \
            -e REACT_APP_TMDBKEY=${{ secrets.REACT_APP_TMDBKEY }} \
            -e REACT_APP_ALAN_KEY=${{ secrets.REACT_APP_ALAN_KEY }} \
            ashwanthsai/sydneyflixtest:latest

      - name: Health Check
        run: |
          sleep 10
          curl -f http://localhost:80 || exit 1