name: Docker Image CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          # We use Docker Personal Access Token as password
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
        context: .
        build-args: |
          REACT_APP_TMDBKEY: ${{ secrets.REACT_APP_TMDBKEY }}
          REACT_APP_ALAN_KEY: ${{ secrets.REACT_APP_ALAN_KEY }}
          TMDB_TEST_EMAIL: ${{ secrets.TMDB_TEST_EMAIL }}
          TMDB_TEST_PASSWORD: ${{ secrets.TMDB_TEST_PASSWORD }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ashwanthsai/sydneyflix:latest
