name: Docker Image CI

on:
  workflow_run:
    workflows: ["Unit + Integration Tests via RTL", "E2E Via Cypress"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ashwanthsai/sydneyflix:latest
          build-args: |
            REACT_APP_TMDBKEY=${{ secrets.REACT_APP_TMDBKEY }}
            REACT_APP_ALAN_KEY=${{ secrets.REACT_APP_ALAN_KEY }}